#!/usr/bin/env bash
# configures and Nginx server to listen on port 80.

# creates a symbolic link (-s option) between the Nginx configuration file
# and the enabled sites directory
ln -sf /etc/nginx/sites-available/default etc/nginx/sites-enabled/default
#restart nginx
service nginx start
#terminates the
kill "$(pgrep 'nginx' | head -1)"
